-- =============================================
-- 国产化API网关平台 - 达梦数据库初始化脚本
-- 版本: 1.0.0
-- 数据库: DM8
-- =============================================

-- 创建表空间
-- CREATE TABLESPACE APIGATEWAY DATAFILE 'APIGATEWAY.DBF' SIZE 128;

-- 创建用户
-- CREATE USER APIGATEWAY IDENTIFIED BY "APIGATEWAY123456" DEFAULT TABLESPACE APIGATEWAY;
-- GRANT DBA TO APIGATEWAY;

-- =============================================
-- 1. 系统用户表
-- =============================================
CREATE TABLE "SYS_USER" (
    "ID" BIGINT NOT NULL,
    "USERNAME" VARCHAR(50) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "REAL_NAME" VARCHAR(50),
    "EMAIL" VARCHAR(100),
    "PHONE" VARCHAR(20),
    "STATUS" INT DEFAULT 1,
    "LAST_LOGIN_TIME" TIMESTAMP,
    "LAST_LOGIN_IP" VARCHAR(50),
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CREATE_USER_ID" BIGINT,
    "UPDATE_USER_ID" BIGINT,
    "DELETED" INT DEFAULT 0,
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "SYS_USER" IS '系统用户表';
COMMENT ON COLUMN "SYS_USER"."ID" IS '用户ID';
COMMENT ON COLUMN "SYS_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "SYS_USER"."PASSWORD" IS '密码(BCrypt加密)';
COMMENT ON COLUMN "SYS_USER"."REAL_NAME" IS '真实姓名';
COMMENT ON COLUMN "SYS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "SYS_USER"."PHONE" IS '手机号';
COMMENT ON COLUMN "SYS_USER"."STATUS" IS '状态:0-禁用,1-启用';
COMMENT ON COLUMN "SYS_USER"."LAST_LOGIN_TIME" IS '最后登录时间';
COMMENT ON COLUMN "SYS_USER"."LAST_LOGIN_IP" IS '最后登录IP';
COMMENT ON COLUMN "SYS_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_USER"."DELETED" IS '删除标识:0-未删除,1-已删除';

-- =============================================
-- 2. API信息表
-- =============================================
CREATE TABLE "API_INFO" (
    "ID" BIGINT NOT NULL,
    "API_NAME" VARCHAR(100) NOT NULL,
    "API_PATH" VARCHAR(255) NOT NULL,
    "API_METHOD" VARCHAR(10) NOT NULL,
    "DATASOURCE_ID" BIGINT,
    "SQL_CONTENT" CLOB,
    "NEED_AUTH" INT DEFAULT 1,
    "ENCRYPT_TYPE" VARCHAR(20),
    "STATUS" INT DEFAULT 0,
    "VERSION" VARCHAR(20) DEFAULT '1.0',
    "DESCRIPTION" VARCHAR(500),
    "REQUEST_EXAMPLE" CLOB,
    "RESPONSE_EXAMPLE" CLOB,
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CREATE_USER_ID" BIGINT,
    "UPDATE_USER_ID" BIGINT,
    "DELETED" INT DEFAULT 0,
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "API_INFO" IS 'API信息表';
COMMENT ON COLUMN "API_INFO"."API_NAME" IS 'API名称';
COMMENT ON COLUMN "API_INFO"."API_PATH" IS 'API路径';
COMMENT ON COLUMN "API_INFO"."API_METHOD" IS '请求方法';
COMMENT ON COLUMN "API_INFO"."DATASOURCE_ID" IS '数据源ID';
COMMENT ON COLUMN "API_INFO"."SQL_CONTENT" IS 'SQL内容';
COMMENT ON COLUMN "API_INFO"."NEED_AUTH" IS '是否需要认证:0-否,1-是';
COMMENT ON COLUMN "API_INFO"."ENCRYPT_TYPE" IS '加密类型:SM4/AES/NONE';
COMMENT ON COLUMN "API_INFO"."STATUS" IS '状态:0-草稿,1-发布,2-下线';
COMMENT ON COLUMN "API_INFO"."VERSION" IS '版本号';

-- =============================================
-- 3. 数据源配置表
-- =============================================
CREATE TABLE "DATASOURCE_CONFIG" (
    "ID" BIGINT NOT NULL,
    "DS_NAME" VARCHAR(100) NOT NULL,
    "DS_TYPE" VARCHAR(50) NOT NULL,
    "JDBC_URL" VARCHAR(500) NOT NULL,
    "USERNAME" VARCHAR(100) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "DRIVER_CLASS" VARCHAR(100),
    "INITIAL_SIZE" INT DEFAULT 5,
    "MAX_ACTIVE" INT DEFAULT 20,
    "MIN_IDLE" INT DEFAULT 5,
    "MAX_WAIT" INT DEFAULT 60000,
    "TEST_QUERY" VARCHAR(100),
    "STATUS" INT DEFAULT 1,
    "HEALTH_STATUS" INT DEFAULT 0,
    "LAST_CHECK_TIME" TIMESTAMP,
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DELETED" INT DEFAULT 0,
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "DATASOURCE_CONFIG" IS '数据源配置表';
COMMENT ON COLUMN "DATASOURCE_CONFIG"."DS_NAME" IS '数据源名称';
COMMENT ON COLUMN "DATASOURCE_CONFIG"."DS_TYPE" IS '数据库类型:DM/MYSQL/ORACLE/SQLSERVER/POSTGRESQL';
COMMENT ON COLUMN "DATASOURCE_CONFIG"."JDBC_URL" IS 'JDBC连接URL';
COMMENT ON COLUMN "DATASOURCE_CONFIG"."STATUS" IS '状态:0-禁用,1-启用';
COMMENT ON COLUMN "DATASOURCE_CONFIG"."HEALTH_STATUS" IS '健康状态:0-异常,1-正常';

-- =============================================
-- 4. 系统日志表
-- =============================================
CREATE TABLE "SYS_LOG" (
    "ID" BIGINT NOT NULL,
    "LOG_TYPE" INT NOT NULL,
    "LOG_TITLE" VARCHAR(100),
    "USER_ID" BIGINT,
    "USERNAME" VARCHAR(50),
    "IP" VARCHAR(50),
    "REQUEST_URL" VARCHAR(500),
    "REQUEST_METHOD" VARCHAR(10),
    "REQUEST_PARAMS" CLOB,
    "RESPONSE_RESULT" CLOB,
    "EXECUTE_TIME" BIGINT,
    "STATUS" INT,
    "EXCEPTION_MSG" CLOB,
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "SYS_LOG" IS '系统日志表';
COMMENT ON COLUMN "SYS_LOG"."LOG_TYPE" IS '日志类型:1-登录日志,2-操作日志,3-异常日志';
COMMENT ON COLUMN "SYS_LOG"."STATUS" IS '状态:0-失败,1-成功';

-- =============================================
-- 5. 创建索引
-- =============================================
CREATE UNIQUE INDEX "UN_USERNAME" ON "SYS_USER"("USERNAME");
CREATE INDEX "IDX_USER_STATUS" ON "SYS_USER"("STATUS");

CREATE INDEX "IDX_API_PATH" ON "API_INFO"("API_PATH");
CREATE INDEX "IDX_API_STATUS" ON "API_INFO"("STATUS");

CREATE INDEX "IDX_DS_NAME" ON "DATASOURCE_CONFIG"("DS_NAME");
CREATE INDEX "IDX_DS_STATUS" ON "DATASOURCE_CONFIG"("STATUS");

CREATE INDEX "IDX_LOG_TYPE" ON "SYS_LOG"("LOG_TYPE");
CREATE INDEX "IDX_LOG_USER_ID" ON "SYS_LOG"("USER_ID");
CREATE INDEX "IDX_LOG_CREATE_TIME" ON "SYS_LOG"("CREATE_TIME");

-- =============================================
-- 6. 初始化数据
-- =============================================

-- 初始化管理员用户 (密码: admin123)
INSERT INTO "SYS_USER" ("ID", "USERNAME", "PASSWORD", "REAL_NAME", "STATUS")
VALUES (1, 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EH', '系统管理员', 1);

-- 初始化默认数据源配置
INSERT INTO "DATASOURCE_CONFIG" ("ID", "DS_NAME", "DS_TYPE", "JDBC_URL", "USERNAME", "PASSWORD", "STATUS", "HEALTH_STATUS")
VALUES (1, '主数据源', 'DM', 'jdbc:dm://localhost:5236/APIGATEWAY', 'SYSDBA', 'SYSDBA', 1, 1);

COMMIT;
